import {
    create,
    NConfigProvider,
    NGlobalStyle,
    NButton,
    NLayout,
    NLayoutHeader,
    NLayoutContent,
    NLayoutFooter,
    NWatermark,
    NGrid,
    NGi,
    NSpace,
    NSwitch,
    NIcon,
    NDivider,
    NEl,
    NAlert,
    NSteps,
    NStep,
    NForm,
    NFormItem,
    NInput,
    NCard,
} from 'naive-ui'

const naive = create({
    components: [
        NConfigProvider,
        NGlobalStyle,
        NButton,
        NLayout,
        NLayoutHeader,
        NLayoutContent,
        NLayoutFooter,
        NWatermark,
        NGrid,
        NGi,
        NSpace,
        NSwitch,
        NIcon,
        NDivider,
        NEl,
        NAlert,
        NSteps,
        NStep,
        NForm,
        NFormItem,
        NInput,
        NCard,
    ]
})

export default naive;